# Generated by Django 3.0.2 on 2020-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='uncategorised', help_text='Category of Website', max_length=31, unique=True),
        ),
    ]
