# Generated by Django 3.0.2 on 2020-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20200324_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Category of Website', max_length=31),
        ),
    ]
